KekRozsakSecurityBundle_login:
        pattern:  /login
        defaults:
                _controller: KekRozsakSecurityBundle:Default:login

KekRozsakSecurityBundle_login_check:
        pattern:  /login_check

KekRozsakSecurityBundle_logout:
        pattern:  /logout

KekRozsakSecurityBundle_registration:
        pattern:  /jelentkezes
        defaults:
                _controller: KekRozsakSecurityBundle:Default:registration

KekRozsakSecurityBundle_reg_success:
        pattern:  /most-varj
        defaults:
                _controller: KekRozsakSecurityBundle:Default:registrationSuccess
