parameters:

services:
        kek_rozsak_security.encoder.crypt:
                class: KekRozsak\SecurityBundle\Service\CryptEncoder
        security.authentication.success_handler:
                class: KekRozsak\SecurityBundle\Security\AuthSuccess
                public: false
                arguments:
                        doctrine: @doctrine
