parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     kekrozsa_dev
    database_user:     kekrozsa_dev
    database_password: Jei5eehe

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_encryption: ssl
    mailer_auth_mode:  login
    mailer_user:       ~
    mailer_password:   ~

    locale:            hu
    secret:            Oob4sahX7Johyoh6uoseev0Quae4Biureih5caGh8puH
