fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

KekRozsakAdminBundle:
    resource: "@KekRozsakAdminBundle/Controller/"
    type:     annotation

KekRozsakFrontBundle:
    resource: "@KekRozsakFrontBundle/Controller/"
    type:     annotation

KekRozsakSecurityBundle:
    resource: "@KekRozsakSecurityBundle/Controller/"
    type:     annotation

