KekRozsakAdminBundle:
        resource: "@KekRozsakAdminBundle/Controller/DefaultController.php"
        type:     annotation

KekRozsakSecurityBundle:
        resource: "@KekRozsakSecurityBundle/Controller/DefaultController.php"
        type:     annotation

KekRozsakFrontBundle_Default:
        resource: "@KekRozsakFrontBundle/Controller/DefaultController.php"
        type:     annotation

KekRozsakFrontBundle_Forum:
        resource: "@KekRozsakFrontBundle/Controller/ForumController.php"
        type:     annotation
