KekRozsak\FrontBundle\Entity\News:
        type: entity
        table: news
        id:
                id:
                        type: integer
                        generator:
                                strategy: AUTO
        fields:
                created_at:
                        type: datetime
                        nullable: false
                updated_at:
                        type: datetime
                        nullable: true
                        default: null
                update_reason:
                        type: text
                        nullable: true
                        default: null
                title:
                        type: string(100)
                        nullable: false
                slug:
                        type: string(100)
                        nullable: false
                        unique: true
                text:
                        type: text
                        nullable: false
        manyToOne:
                created_by:
                        targetEntity: User
                        nullable: false
                        inversedBy: news
                updated_by:
                        targetEntity: User
                        nullable: true
                        default: null
