KekRozsak\FrontBundle\Entity\Role:
        type: entity
        table: roles
        id:
                id:
                        type: integer
                        generator:
                                strategy: AUTO
        fields:
                name:
                        type: string(100)
                        nullable: false
                display_name:
                        type: string(100)
                        nullable: false
                can_be_assigned:
                        type: boolean
                        default: false
        manyToMany:
                included_roles:
                        targetEntity: Role
                        joinTable:
                                name: role_hierarchy
                                joinColumns:
                                        parent_role_id:
                                                referencedColumnName: id
                                inverseJoinColumns:
                                        child_role_id:
                                                referencedColumnName: id
                                
