KekRozsak\FrontBundle\Entity\User:
        type: entity
        table: users
        id:
                id:
                        type: integer
                        generator:
                                strategy: AUTO
        fields:
                username:
                        type: string(50)
                        nullable: false
                password:
                        type: string(50)
                        nullable: false
                email:
                        type: string(50)
                        nullable: false
                registered_at:
                        type: datetime
                display_name:
                        type: string(50)
                        nullable: false
        manyToMany:
                roles:
                        targetEntity: Role
