KekRozsakFrontBundle_homepage:
        pattern:  /
        defaults:
                _controller: KekRozsakFrontBundle:Default:homepage

KekRozsakFrontBundle_article:
        pattern:  /cikk/{articleSlug}
        defaults:
                _controller: KekRozsakFrontBundle:Default:article

KekRozsakFrontBundle_forum_main:
        pattern:  /forum
        defaults:
                _controller: KekRozsakFrontBundle:Forum:main

KekRozsakFrontBundle_forum_topic_list:
        pattern:  /forum/{topicGroupSlug}
        defaults:
                _controller: KekRozsakFrontBundle:Forum:topicList

KekRozsakFrontBundle_forum_post_list:
        pattern:  /forum/{topicGroupSlug}/{topicSlug}
        defaults:
                _controller: KekRozsakFrontBundle:Forum:postList
