KekRozsakFrontBundle_homepage:
        pattern:  /
        defaults:
                _controller: KekRozsakFrontBundle:Default:article
                articleSlug: aktualis

KekRozsakFrontBundle_article:
        pattern:  /cikk/{$articleSlug}
        defaults:
                _controller: KekRozsakFrontBundle:Default:article
